version: '3.4'

services:
    catalogdb:
        container_name: catalogdb
        restart: always
        volumes:
            - ${WEBAPP_STORAGE_HOME}/site:/data/db
        ports:
            - "27017:27017"

    basketdb:
        container_name: basketdb
        restart: always
        ports:
            - "6379:6379"

    catalog.api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "CatalogDatabaseSettings:ConnectionString=mongodb://localhost:27017"
        depends_on:
            - catalogdb
        ports:
            - "8000:80"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https

    basket.api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "ConnectionStrings:Redis=basketdb:6379"
        depends_on:
            - basketdb
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https
        ports:
            - "8001:80"